export default {
"ac": "Ilhas Ascensão",
"ad": "Andorra",
"ae": "Emirados Árabes Unidos",
"af": "Afeganistão",
"ag": "Antígua e Barbuda",
"ai": "Anguilla",
"al": "Albânia",
"am": "Armênia",
"an": "Antilhas Holandesas",
"ao": "Angola",
"aq": "Antártida",
"ar": "Argentina",
"as": "Samoa Americana",
"at": "Áustria",
"au": "Austrália",
"aw": "Aruba",
"az": "Azerbaijão",
"ba": "Bósnia e Herzegovina",
"bb": "Barbados",
"bd": "Bangladesh",
"be": "Bélgica",
"bf": "Burkina Faso",
"bg": "Bulgária",
"bh": "Bahrein",
"bi": "Burundi",
"bj": "Benin",
"bm": "Bermudas",
"bn": "Brunei Darussalem",
"bo": "Bolívia",
"br": "Brasil",
"bs": "Bahamas",
"bt": "Butão",
"bv": "Ilha Bouvet",
"bw": "Botsuana",
"by": "Bielorrúsia",
"bz": "Belize",
"ca": "Canadá",
"cc": "Ilhas Cocos",
"cd": "República Democrática do Congo",
"cf": "República Centro-Africana",
"cg": "República do Congo",
"ch": "Suíça",
"ci": "Costa do Marfim",
"ck": "Ilhas Cook",
"cl": "Chile",
"cm": "Camarões",
"cn": "China",
"co": "Colômbia",
"cr": "Costa Rica",
"cu": "Cuba",
"cv": "Cabo Verde",
"cx": "Ilha Natal",
"cy": "Chipre",
"cz": "República Tcheca",
"de": "Alemanha",
"dj": "Djibouti",
"dk": "Dinamarca",
"dm": "Dominica",
"do": "República Dominicana",
"dz": "Argélia",
"ec": "Equador",
"ee": "Estônia",
"eg": "Egito",
"er": "Eritreia",
"es": "Espanha",
"et": "Etiopia",
"fi": "Finlândia",
"fj": "Fiji",
"fk": "Malvinas",
"fm": "Estados Federados da Micronésia",
"fo": "ilhas Feroé",
"fr": "França",
"ga": "Gabão",
"gb": "Reino Unido",
"gd": "Granada",
"ge": "Geórgia",
"gf": "Guiana Francesa",
"gg": "Guernsey",
"gh": "Gana",
"gi": "Gibraltar",
"gl": "Groenlândia",
"gm": "Gâmbia",
"gn": "Guiné",
"gp": "Guadalupe",
"gq": "Guiné Equatorial",
"gr": "Grécia",
"gs": "Ilhas Géorgia do Sul e Sandwich do Sul",
"gt": "Guatemala",
"gu": "Guam",
"gw": "Guiné-Bissau",
"gy": "Guiana",
"hk": "Hong Kong",
"hm": "Ilha Heard e Ilhas McDonald",
"hn": "Honduras",
"hr": "Croácia",
"ht": "Haiti",
"hu": "Hungria",
"id": "Indonésia",
"ie": "Irlanda",
"il": "Israel",
"im": "Ilhas de Man",
"in": "Índia",
"io": "Território Britânico do oceano Índico",
"iq": "Iraque",
"ir": "Irã",
"is": "Islândia",
"it": "Itália",
"je": "Jersey",
"jm": "Jamaica",
"jo": "Jordânia",
"jp": "Japão",
"ke": "Quênia",
"kg": "Quirguistão",
"kh": "Camboja",
"ki": "Kiribati",
"km": "Comores",
"kn": "São Cristovão e Nevis",
"kr": "Coreia do Sul",
"kw": "Kuwait",
"ky": "Ilhas Caiman",
"kz": "Cazaquistão",
"la": "Laos",
"lb": "Líbano",
"lc": "Santa Lúcia",
"li": "Lienchtestein",
"lk": "Sri Lanka",
"lr": "Libéria",
"ls": "Lesoto",
"lt": "Lituânia",
"lu": "Luxemburgo",
"lv": "Letônia",
"ly": "Líbia",
"ma": "Marrocos",
"mc": "Mônaco",
"md": "Moldávia",
"me": "Montenegro",
"mg": "Madagascar",
"mh": "Ilhas Marshall",
"mk": "Macedônia",
"ml": "Mali",
"mm": "Myanmar",
"mn": "mongólia",
"mo": "Macau",
"mp": "Marianas Setentrionais",
"mq": "Martinica",
"mr": "Mauritânia",
"ms": "Montserrat",
"mt": "Malta",
"mu": "Maurício",
"mv": "Maldivas",
"mw": "Malaxi",
"mx": "México",
"my": "Malásia",
"mz": "Moçambique",
"nb": "Namíbia",
"nc": "Nova Caledônia",
"ne": "Níger",
"nf": "Ilha Norfolk",
"ng": "Nigéria",
"ni": "Nicarágua",
"nl": "Holanda",
"no": "Noruega",
"np": "Nepal",
"nr": "Nauru",
"nu": "Niue",
"nz": "Nova Zelândia",
"om": "Omã",
"pa": "Panamá",
"pe": "Peru",
"pf": "Polinésia Francesa",
"pg": "Papua-Nova Guiné",
"ph": "Filipinas",
"pk": "Paquistão",
"pl": "Polônia",
"pm": "Saint-Pierre e Miquelon",
"pn": "Ilhas Pitcairn",
"pr": "Porto Rico",
"ps": "Territórios palestinos (Cisjordâni, Faixa de Gaz, etc)",
"pt": "Portugal",
"pw": "Palau",
"py": "Paraguai",
"qa": "Catar",
"re": "Reunião",
"ro": "Romênia",
"ru": "Rússia",
"rw": "Ruanda",
"sa": "Arábia Saudita",
"sb": "Ilhas Salomão",
"sd": "Sudão",
"se": "Suécia",
"sg": "Singapura",
"sh": "Santa Helena",
"si": "Eslovênia",
"sj": "Ilhas Svalbard e Jan Mayen",
"sk": "Eslováquia",
"sl": "Serra Leo",
"sm": "San Marino",
"sn": "Senegal",
"so": "Somália",
"sr": "Suriname",
"rs": "Sérvia",
"ss": "Sudão do Sul",
"st": "São Tomé e Príncipe",
"su": "Antiga União Soviética",
"sv": "São Salvador",
"sy": "Síria",
"sz": "Suazilândia",
"tc": "Ilhas Turcas e Caicos",
"td": "Chade",
"tf": "Terras Austrais e Antárticas Francesas",
"tg": "Togo",
"th": "Tailânida",
"tj": "Tajiquistão",
"tk": "Tokelau",
"tl": "Timor Leste",
"tm": "Turcomenistão",
"tn": "Tunísia",
"to": "Tonga",
"tr": "Turquia",
"tt": "Trinidade e Tobago",
"tv": "Tuvalu",
"tw": "Taiwan",
"tz": "Tanzânia",
"ua": "Ucrânia",
"ug": "Uganda",
"uk": "Reino Unido",
"um": "Ilhas Menores Distantes dos Estados Unidos", 
"us": "Estados Unidos da América",
"ui": "Uruguai",
"uz": "Uzbequistão",
"va": "Vaticano",
"vc": "São Vicente e Granadinas",
"ve": "Venezuela",
"vg": "Ilhas Virgens britãnicas",
"vi": "Ilhas Virgens Americanas",
"vn": "Vietnã",
"vu": "Vanuatu",
"wf": "Wallis e Futuna",
"ws": "Samoa",
"ye": "Iemen",
"yt": "Mayotte",
"yu": "Iuguslávia",
"za": "África do Sul",
"zm": "Zâmbia",
"zw": "Zimbábue",
"sc": "Escócia" 
}